### ISSUE TITLE
Nested properties?

### ISSUE THREAD

**Issue by Sivli-Embir** [rclai/meteor-document-methods#3]
I have not tested the code yet but I was eyeing your tests. I don't see anything on nested properties. Can you do things like:

``` js
var obj = Objs.findOne({})
// obj.foo.bar === 'works'
// obj.foo.bin === undefined
obj.foo.bin = 'still works'
obj.$save()

var obj = Objs.findOne({})
// obj.foo.bin === 'still works'
```

**Comment by rclai** [comment]
Will do, I have a couple more tests to do.

**Comment by Sivli-Embir** [comment]
Success I take it? I have added this to my "framepack" https://github.com/Meteor-Reaction/Gravity, let me know if you want to do more from a model perspective. Finding a way to hook a validate before to this would be a neat trick.

**Comment by rclai** [comment]
Yup.

Cool, thanks for adding this in there. When I thought of creating a package, I did think about models, like:

```
var todo = new Todo();
todo.title = 'title';
todo.done = false;
todo.save();
```

But I feel like it would've added way too much complexity, but then I saw this guy create [this package](https://atmospherejs.com/nucleuside/smart-models) and I kind of thought maybe I could do it, but then a lot of people have started using collection helpers, so I'm kind of stuck figuring out how to best implement it in the most package compatible way, while at the same time not adding too much bloat on top of Mongo's functionality. 

P.S. - I'm still working on the mongo constructor injector package, so don't worry I haven't forgotten.

**Comment by Sivli-Embir** [comment]
So I have gone down this road a number of times (Just look at https://github.com/Meteor-Reaction/).

My current idea for models are thus:

``` js
//This is the model
myModel = new Mongo.Collection('my-model') //Also null would work non-persistance model
myModel.addSchema({ //who, what, where I am not sure yet but some kind of schema
  myProp: {
    validate: function or Object (like String)
  }
}) 
myModel.helpers({})
myModel.instanceHelpers({}) //would just collection transform.
```

The reason for that is because it will keep the Meteor JS "purists" happy. But then we could create a fully optional helper:

``` js
myModel = new Model({
  collection: string or null,
  schema: theSchema,
  helpers: Class helpers,
  instance: transform
})
```

Then of course we would want things like:

``` js
var myInstance = new myModel()
myInstance.title = 'title';
myInstance.done = false;
if (myInstance.$valid) { //I like the $ namespacing (even if its a mongo thing)
  myInstance.$save();
}
```

**Comment by Sivli-Embir** [comment]
Also no worries on the mongo constructor injector, I am just adding it manually: https://github.com/Meteor-Reaction/Candid/blob/master/temp.js
