### ISSUE TITLE
crash on start if package "accounts-base" is not installed

### ISSUE THREAD

**Issue by krawalli** [rclai/meteor-document-methods#6]
With latest addition to have the methods on the users collection, startup of meteor breaks, if the application has not "accounts-base" package installed.

Please add a check if this package is installed before applying the methods to user collection.

``` javascript
if (!!Package['accounts-base']) {
 ...apply to users collection
}
```

**Comment by krawalli** [comment]
..and it depends on the package loading order. So maybe a simple if (Meteor.users !== undefined) could work

**Comment by rclai** [comment]
Thanks for pointing this out.
