### ISSUE TITLE
Troubles running ToDo Demo App

### ISSUE THREAD

**Issue by Digital-Thor** [rclai/meteor-document-methods#7]
Thanks for putting this package together Richard.  It looks very helpful.

I'm trying to learn to use it, but having troubles getting the ToDo demo code to work.  I started by creating a Meteor app then added your meteor-documents-methods package.  I used only your app.js and template demo code, but added the following before the template code:

```
<head>
  <title>Todo List</title>
</head>

<body>
    {{> todos}}
</body>
```

Before I could see anything on the page, I had to inject a Mongo document directly using the console MiniMongo command `Todos.insert({title: 'first todo', done:false })` .  Duplicate and Delete buttons work, but Add button reported:

```
Uncaught ReferenceError: e is not definedmongohelpers.js?b94e24dd2e01927a2dae4c4c835c58c447e0ade2:19 
Template.todos.events.submit .add-tagtemplate.js:278 
(anonymous function)view.js:760 
(anonymous function)view.js:414 
Blaze._withCurrentViewview.js:759 
(anonymous function)events.js:47 
(anonymous function)jquery.js:4665 
jQuery.event.dispatchjquery.js:4333 
jQuery.event.add.elemData.handle
```

Any guidance will be much appreciated.

**Comment by rclai** [comment]
Sorry about that, my example code was wrong, I fixed it now.
